server.port: 8085
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sksmith/smfg-configs
          searchPaths: '{application}'
          force-pull: true